CREATE ROLE adminR;
GRANT CREATE SESSION,
       CREATE TABLE,
       CREATE VIEW,
       CREATE PROCEDURE,
       CREATE SEQUENCE,
      CREATE TRIGGER,
      DROP ANY TABLE,
      ALTER ANY TABLE,
      SELECT ANY TABLE,
      INSERT ANY TABLE,
      UPDATE ANY TABLE,
      DELETE ANY TABLE,
      RESTRICTED SESSION
TO adminR;

CREATE User AdminUser IDENTIFIED BY 111;
grant ADMINR to adminUser;

CREATE ROLE moderatorR;
GRANT EXECUTE ON ADMINUSER.DELBLOG TO moderatorR;
GRANT EXECUTE ON ADMINUSER.DELUSERBYID TO moderatorR;
GRANT EXECUTE ON ADMINUSER.DELPOST TO moderatorR;
GRANT EXECUTE ON ADMINUSER.DELCOMMENT TO moderatorR;
GRANT EXECUTE ON ADMINUSER.UPDBLOG TO moderatorR;
GRANT EXECUTE ON ADMINUSER.UPDCOMMENT TO moderatorR;
GRANT EXECUTE ON ADMINUSER.UPDPOST TO moderatorR;
GRANT EXECUTE ON ADMINUSER.UPDUSERBYID TO moderatorR;

GRANT EXECUTE ON ADMINUSER.GETALLBLOGS TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETALLPOSTS TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETBLOGBYID TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETBLOGFORUSER TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETCOMMENTBYID TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETCOMMENTSFORPOST TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTFAVFORPOST TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTFAVFORUSER TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTLIKE TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTSUBFORBLOG TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTSUBFORUSER TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETPOSTBYID TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETPOSTFORBLOG TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETUSERBYEMAIL TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETUSERBYID TO moderatorR;
GRANT EXECUTE ON ADMINUSER.GETUSERBYLOGIN TO moderatorR;
GRANT EXECUTE ON ADMINUSER.HASH_PASSWORD TO moderatorR;
GRANT EXECUTE ON ADMINUSER.SEARCH TO moderatorR;

CREATE User ModeratorUser IDENTIFIED BY 111;
grant ModeratorR to ModeratorUser;

CREATE ROLE userR;
GRANT EXECUTE ON ADMINUSER.ADDBLOG TO userR;
GRANT EXECUTE ON ADMINUSER.ADDCOMMENT TO userR;
GRANT EXECUTE ON ADMINUSER.ADDPOST TO userR;
GRANT EXECUTE ON ADMINUSER.ADDUSER TO userR;
GRANT EXECUTE ON ADMINUSER.ADDVIEWPOST TO userR;
GRANT EXECUTE ON ADMINUSER.DELBLOG TO userR;
GRANT EXECUTE ON ADMINUSER.DELCOMMENT TO userR;
GRANT EXECUTE ON ADMINUSER.DELPOST TO userR;
GRANT EXECUTE ON ADMINUSER.DELUSERBYID TO userR;
GRANT EXECUTE ON ADMINUSER.SEND_MESSAGE TO userR;
GRANT EXECUTE ON ADMINUSER.UPDBLOG TO userR;
GRANT EXECUTE ON ADMINUSER.UPDCOMMENT TO userR;
GRANT EXECUTE ON ADMINUSER.UPDFAVORITE TO userR;
GRANT EXECUTE ON ADMINUSER.UPDLIKE TO userR;
GRANT EXECUTE ON ADMINUSER.UPDPOST TO userR;
GRANT EXECUTE ON ADMINUSER.UPDSUBSCRIPTION TO userR;
GRANT EXECUTE ON ADMINUSER.UPDUSERBYID TO userR;
GRANT EXECUTE ON ADMINUSER.GETALLBLOGS TO userR;
GRANT EXECUTE ON ADMINUSER.GETALLPOSTS TO userR;
GRANT EXECUTE ON ADMINUSER.GETBLOGBYID TO userR;
GRANT EXECUTE ON ADMINUSER.GETBLOGFORUSER TO userR;
GRANT EXECUTE ON ADMINUSER.GETCOMMENTBYID TO userR;
GRANT EXECUTE ON ADMINUSER.GETCOMMENTSFORPOST TO userR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTFAVFORPOST TO userR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTFAVFORUSER TO userR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTLIKE TO userR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTSUBFORBLOG TO userR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTSUBFORUSER TO userR;
GRANT EXECUTE ON ADMINUSER.GETPOSTBYID TO userR;
GRANT EXECUTE ON ADMINUSER.GETPOSTFORBLOG TO userR;
GRANT EXECUTE ON ADMINUSER.GETUSERBYEMAIL TO userR;
GRANT EXECUTE ON ADMINUSER.GETUSERBYID TO userR;
GRANT EXECUTE ON ADMINUSER.GETUSERBYLOGIN TO userR;
GRANT EXECUTE ON ADMINUSER.HASH_PASSWORD TO userR;
GRANT EXECUTE ON ADMINUSER.SEARCH TO userR;

CREATE User UserUser IDENTIFIED BY 111;
grant userr to userUser;

CREATE ROLE guestR;
GRANT EXECUTE ON ADMINUSER.ADDUSER TO guestR;
GRANT EXECUTE ON ADMINUSER.ADDVIEWPOST TO guestR;
GRANT EXECUTE ON ADMINUSER.GETALLBLOGS TO guestR;
GRANT EXECUTE ON ADMINUSER.GETALLPOSTS TO guestR;
GRANT EXECUTE ON ADMINUSER.GETBLOGBYID TO guestR;
GRANT EXECUTE ON ADMINUSER.GETBLOGFORUSER TO guestR;
GRANT EXECUTE ON ADMINUSER.GETCOMMENTBYID TO guestR;
GRANT EXECUTE ON ADMINUSER.GETCOMMENTSFORPOST TO guestR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTFAVFORPOST TO guestR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTFAVFORUSER TO guestR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTLIKE TO guestR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTSUBFORBLOG TO guestR;
GRANT EXECUTE ON ADMINUSER.GETCOUNTSUBFORUSER TO guestR;
GRANT EXECUTE ON ADMINUSER.GETPOSTBYID TO guestR;
GRANT EXECUTE ON ADMINUSER.GETPOSTFORBLOG TO guestR;
GRANT EXECUTE ON ADMINUSER.GETUSERBYEMAIL TO guestR;
GRANT EXECUTE ON ADMINUSER.GETUSERBYID TO guestR;
GRANT EXECUTE ON ADMINUSER.GETUSERBYLOGIN TO guestR;
GRANT EXECUTE ON ADMINUSER.HASH_PASSWORD TO guestR;
GRANT EXECUTE ON ADMINUSER.SEARCH TO guestR;

CREATE User guestUser IDENTIFIED BY 111;
grant guestR to guestUser;


